### ISSUE TITLE
Boilerplates, examples

### ISSUE THREAD

**Issue by eshimischi** [spaceonfire/spaceonfire#24]
Not an issue or bug, just curious if you have any real projects/boilerplates based on your 3.x branch. Would love to see the usage of Cycle-Bridge/Collection packages, for instance.

Thanks in advanced!

**Comment by tntrex** [comment]
Currently I working on a project on my job, that based on these packages. Probably I can prepare gist or example repo to show concepts. I will post link here when it will be done.

**Comment by eshimischi** [comment]
Would be awesome, thanks in advanced! I've found your packages are pretty suitable for my projects, just need more details about proper usage

**Comment by tntrex** [comment]
Just finished demo app repository [hustlahusky/spaceonfire-demo-app](https://github.com/hustlahusky/spaceonfire-demo-app). Tried to make it as simple as possible and show main use cases with cycle orm. Feel free to get in touch with me using telegram for further questions.

**Comment by eshimischi** [comment]
Neat! Thanks, mate, really appreciate your work!
