### ISSUE TITLE
What class-string type means?

### ISSUE THREAD

**Issue by eshimischi** [spaceonfire/spaceonfire#25]
https://github.com/spaceonfire/spaceonfire/blob/a2c36250b03674a8d7f7033eb4a5367c5b1868fb/pkg/type/src/InstanceOfType.php#L15

is this a typo or?

**Comment by eshimischi** [comment]
Seems like `@phpstan-var class-string`

**Comment by tntrex** [comment]
It is not a typo. Property with `class-string` expects fully qualified class name as string. This notation supported by static analysis tools (PHPStan / Psalm) and PhpStorm. Sometimes I use `@phpstan-var` directly in code to help PHPStan clarify variable type.
